// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.12.4
// source: proto/atlas.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConsensusMessage_Type int32

const (
	ConsensusMessage_PRE_PREPARE ConsensusMessage_Type = 0
	ConsensusMessage_PREPARE     ConsensusMessage_Type = 1
	ConsensusMessage_COMMIT      ConsensusMessage_Type = 2
)

// Enum value maps for ConsensusMessage_Type.
var (
	ConsensusMessage_Type_name = map[int32]string{
		0: "PRE_PREPARE",
		1: "PREPARE",
		2: "COMMIT",
	}
	ConsensusMessage_Type_value = map[string]int32{
		"PRE_PREPARE": 0,
		"PREPARE":     1,
		"COMMIT":      2,
	}
)

func (x ConsensusMessage_Type) Enum() *ConsensusMessage_Type {
	p := new(ConsensusMessage_Type)
	*p = x
	return p
}

func (x ConsensusMessage_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConsensusMessage_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_atlas_proto_enumTypes[0].Descriptor()
}

func (ConsensusMessage_Type) Type() protoreflect.EnumType {
	return &file_proto_atlas_proto_enumTypes[0]
}

func (x ConsensusMessage_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConsensusMessage_Type.Descriptor instead.
func (ConsensusMessage_Type) EnumDescriptor() ([]byte, []int) {
	return file_proto_atlas_proto_rawDescGZIP(), []int{1, 0}
}

type VMState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Memory []byte `protobuf:"bytes,1,opt,name=memory,proto3" json:"memory,omitempty"`
	Pc     uint32 `protobuf:"varint,2,opt,name=pc,proto3" json:"pc,omitempty"`
	Acc    int32  `protobuf:"varint,3,opt,name=acc,proto3" json:"acc,omitempty"`
}

func (x *VMState) Reset() {
	*x = VMState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_atlas_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VMState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VMState) ProtoMessage() {}

func (x *VMState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_atlas_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VMState.ProtoReflect.Descriptor instead.
func (*VMState) Descriptor() ([]byte, []int) {
	return file_proto_atlas_proto_rawDescGZIP(), []int{0}
}

func (x *VMState) GetMemory() []byte {
	if x != nil {
		return x.Memory
	}
	return nil
}

func (x *VMState) GetPc() uint32 {
	if x != nil {
		return x.Pc
	}
	return 0
}

func (x *VMState) GetAcc() int32 {
	if x != nil {
		return x.Acc
	}
	return 0
}

type ConsensusMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type  ConsensusMessage_Type `protobuf:"varint,1,opt,name=type,proto3,enum=atlas.ConsensusMessage_Type" json:"type,omitempty"`
	View  int64                 `protobuf:"varint,2,opt,name=view,proto3" json:"view,omitempty"`
	State *VMState              `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
}

func (x *ConsensusMessage) Reset() {
	*x = ConsensusMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_atlas_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConsensusMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsensusMessage) ProtoMessage() {}

func (x *ConsensusMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_atlas_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsensusMessage.ProtoReflect.Descriptor instead.
func (*ConsensusMessage) Descriptor() ([]byte, []int) {
	return file_proto_atlas_proto_rawDescGZIP(), []int{1}
}

func (x *ConsensusMessage) GetType() ConsensusMessage_Type {
	if x != nil {
		return x.Type
	}
	return ConsensusMessage_PRE_PREPARE
}

func (x *ConsensusMessage) GetView() int64 {
	if x != nil {
		return x.View
	}
	return 0
}

func (x *ConsensusMessage) GetState() *VMState {
	if x != nil {
		return x.State
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_atlas_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_atlas_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_atlas_proto_rawDescGZIP(), []int{2}
}

var File_proto_atlas_proto protoreflect.FileDescriptor

var file_proto_atlas_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x74, 0x6c, 0x61, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x61, 0x74, 0x6c, 0x61, 0x73, 0x22, 0x43, 0x0a, 0x07, 0x56, 0x4d,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x12, 0x0e, 0x0a,
	0x02, 0x70, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x70, 0x63, 0x12, 0x10, 0x0a,
	0x03, 0x61, 0x63, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x61, 0x63, 0x63, 0x22,
	0xb0, 0x01, 0x0a, 0x10, 0x43, 0x6f, 0x6e, 0x73, 0x65, 0x6e, 0x73, 0x75, 0x73, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x30, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x61, 0x74, 0x6c, 0x61, 0x73, 0x2e, 0x43, 0x6f, 0x6e, 0x73, 0x65,
	0x6e, 0x73, 0x75, 0x73, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x76, 0x69, 0x65, 0x77, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x76, 0x69, 0x65, 0x77, 0x12, 0x24, 0x0a, 0x05, 0x73, 0x74,
	0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x61, 0x74, 0x6c, 0x61,
	0x73, 0x2e, 0x56, 0x4d, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65,
	0x22, 0x30, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0f, 0x0a, 0x0b, 0x50, 0x52, 0x45, 0x5f,
	0x50, 0x52, 0x45, 0x50, 0x41, 0x52, 0x45, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x50, 0x52, 0x45,
	0x50, 0x41, 0x52, 0x45, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x43, 0x4f, 0x4d, 0x4d, 0x49, 0x54,
	0x10, 0x02, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x32, 0x46, 0x0a, 0x0b, 0x4e,
	0x6f, 0x64, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x37, 0x0a, 0x0e, 0x52, 0x65,
	0x63, 0x65, 0x69, 0x76, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x17, 0x2e, 0x61,
	0x74, 0x6c, 0x61, 0x73, 0x2e, 0x43, 0x6f, 0x6e, 0x73, 0x65, 0x6e, 0x73, 0x75, 0x73, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x0c, 0x2e, 0x61, 0x74, 0x6c, 0x61, 0x73, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x42, 0x35, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x48, 0x4d, 0x5a, 0x45, 0x6c, 0x69, 0x64, 0x72, 0x69, 0x73, 0x73, 0x69, 0x2f, 0x61,
	0x74, 0x6c, 0x61, 0x73, 0x2d, 0x76, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x2d, 0x6d, 0x61, 0x63,
	0x68, 0x69, 0x6e, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_proto_atlas_proto_rawDescOnce sync.Once
	file_proto_atlas_proto_rawDescData = file_proto_atlas_proto_rawDesc
)

func file_proto_atlas_proto_rawDescGZIP() []byte {
	file_proto_atlas_proto_rawDescOnce.Do(func() {
		file_proto_atlas_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_atlas_proto_rawDescData)
	})
	return file_proto_atlas_proto_rawDescData
}

var file_proto_atlas_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_atlas_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_atlas_proto_goTypes = []any{
	(ConsensusMessage_Type)(0), // 0: atlas.ConsensusMessage.Type
	(*VMState)(nil),            // 1: atlas.VMState
	(*ConsensusMessage)(nil),   // 2: atlas.ConsensusMessage
	(*Empty)(nil),              // 3: atlas.Empty
}
var file_proto_atlas_proto_depIdxs = []int32{
	0, // 0: atlas.ConsensusMessage.type:type_name -> atlas.ConsensusMessage.Type
	1, // 1: atlas.ConsensusMessage.state:type_name -> atlas.VMState
	2, // 2: atlas.NodeService.ReceiveMessage:input_type -> atlas.ConsensusMessage
	3, // 3: atlas.NodeService.ReceiveMessage:output_type -> atlas.Empty
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_atlas_proto_init() }
func file_proto_atlas_proto_init() {
	if File_proto_atlas_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_atlas_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*VMState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_atlas_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ConsensusMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_atlas_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_atlas_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_atlas_proto_goTypes,
		DependencyIndexes: file_proto_atlas_proto_depIdxs,
		EnumInfos:         file_proto_atlas_proto_enumTypes,
		MessageInfos:      file_proto_atlas_proto_msgTypes,
	}.Build()
	File_proto_atlas_proto = out.File
	file_proto_atlas_proto_rawDesc = nil
	file_proto_atlas_proto_goTypes = nil
	file_proto_atlas_proto_depIdxs = nil
}
